name: Update YouTube Videos
on:
  schedule:
    - cron: "0 0 * * *" # Runs every 24 hours at midnight UTC
  workflow_dispatch: # Allows you to trigger it manually anytime

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch YouTube videos
        uses: DenverCoder1/github-readme-youtube-feed@v1.0.0
        with:
          channel_id: UCSPtcKpk73_vuQnVhJHfbZA
          max_videos: 6
          template: |
            <div style="display: inline-block; margin: 10px;">
              <a href="https://www.youtube.com/watch?v={{id}}" target="_blank">
                <img src="https://img.youtube.com/vi/{{id}}/mqdefault.jpg" width="300" alt="{{title}}">
              </a>
              <p align="center"><strong>{{title}}</strong></p>
            </div>

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Updated YouTube videos"
