name: Update YouTube Videos
on:
  schedule:
    - cron: "0 0 * * *" # Runs every 24 hours at midnight UTC
  workflow_dispatch: # Manual trigger

# ✅ Required so GitHub Actions can push changes to your README.md
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Insert YouTube cards into README
        uses: DenverCoder1/github-readme-youtube-cards@v1.8.0
        with:
          channel_id: UCSPtcKpk73_vuQnVhJHfbZA
          max_videos: 6
          readme_path: README.md
          commit_message: "🔄 Updated YouTube videos"
